/amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    max_beams: 60
    num_particles: 50
    sigma_hit: 0.2
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.1
    z_rand: 0.9

